@startuml database_schema
hide circle

class player {
  {static} id : INTEGER
  {abstract} address_id : INTEGER
  ..
  last_name : VARCHAR
  first_name : VARCHAR
  birthdate : TIMESTAMP
  email : VARCHAR
  phone : VARCHAR
}

class event {
  {static} id : INTEGER
  {abstract} address_id : INTEGER
  ..
  name : VARCHAR
  description : TEXT
  date : TIMESTAMP
}

class participant {
  {static} player_id : INTEGER
  {static} event_id : INTEGER
  ..
  documents : JSONB
}

class sponsor {
  {static} id : INTEGER
  {abstract} address_id : INTEGER
  ..
  name : VARCHAR
  siren : VARCHAR
  logo : BLOB
}

class financing {
  {static} event_id : INTEGER
  {static} sponsor_id : INTEGER
  ..
  amount : NUMBER(12,2)
}

class address {
  {static} id : INTEGER
  ..
  street_number : VARCHAR
  street_name : VARCHAR
  postal_code : VARCHAR
  city : VARCHAR
  gps_coordinates : VARCHAR
}

player -up- participant : inscrit
participant -right- event : participe
event -- financing : financé
sponsor -right- financing : finance
player -- address : réside
event -- address : à lieu à
sponsor -- address : siège à

@enduml